# .github/workflows/create-iso.yml

name: Create ISO from Release ZIP

on:
  release:
    types: [published]

env:
  ZIP_NAME: "sayooshi-files.zip"

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # (1) リリースから指定されたZIPファイルをダウンロード
      - name: Download Release ZIP Asset
        uses: dsaltares/download-release-asset@v1 # <-- ★★★ 変更点 ★★★
        with:
          file: ${{ env.ZIP_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }} # (注) このアクションでは 'repo-token' ではなく 'token' を使います

      # (2) ISOイメージ作成ツールをインストール
      - name: Install genisoimage
        run: sudo apt-get update && sudo apt-get install -y genisoimage

      # (3) ダウンロードしたZIPを解凍
      - name: Unzip Asset
        run: |
          mkdir -p isocontents
          unzip ${{ env.ZIP_NAME }} -d isocontents

      # (4) isocontentsディレクトリからISOファイルを作成
      - name: Create ISO Image
        run: |
          genisoimage -V SAYOOSHI -J -r -o sayooshi.iso isocontents/
      
      # (5) 作成したISOファイルを同じリリースにアップロード
      - name: Upload ISO to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sayooshi.iso
          asset_name: sayooshi.iso
          tag: ${{ github.ref }}
          overwrite: true
