# .github/workflows/create-iso.yml

name: Create ISO from Release ZIP

# このワークフローが実行されるタイミングを指定
on:
  # 1. 新しいリリースが公開されたら実行
  release:
    types: [published]
  
  # 2. 手動で実行できるようにする (workflow_dispatch)
  workflow_dispatch:
    inputs:
      tag:
        description: 'ISO変換の対象となるリリースのタグ名 (例: v1.0)'
        required: true
      zip_name:
        description: '変換元のZIPファイル名'
        required: true
        default: 'sayooshi-files.zip'

# リリース時に使われるZIPファイル名を定義
env:
  RELEASE_ZIP_NAME: "sayooshi-files.zip"

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # (1) 実行方法に応じて、対象のタグ名とZIPファイル名を変数にセットする
      - name: Set target variables
        id: get_vars
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "ZIP_NAME=${{ env.RELEASE_ZIP_NAME }}" >> $GITHUB_OUTPUT
          else
            echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
            echo "ZIP_NAME=${{ github.event.inputs.zip_name }}" >> $GITHUB_OUTPUT
          fi

      # (2) リリースから指定されたZIPファイルをダウンロード
      - name: Download Release ZIP Asset
        uses: dsaltares/download-release-asset@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get_vars.outputs.TAG_NAME }}
          file: ${{ steps.get_vars.outputs.ZIP_NAME }}
          
      # (3) ISOイメージ作成ツールをインストール
      - name: Install genisoimage
        run: sudo apt-get update && sudo apt-get install -y genisoimage

      # (4) ダウンロードしたZIPを解凍
      - name: Unzip Asset
        run: |
          mkdir -p isocontents
          unzip "${{ steps.get_vars.outputs.ZIP_NAME }}" -d isocontents

      # (5) isocontentsディレクトリからISOファイルを作成
      - name: Create ISO Image
        run: |
          genisoimage -V SAYOOSHI -J -r -o sayooshi.iso isocontents/
      
      # (6) 作成したISOファイルを同じリリースにアップロード
      - name: Upload ISO to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get_vars.outputs.TAG_NAME }}
          file: sayooshi.iso
          asset_name: sayooshi.iso
          overwrite: true
